### ISSUE TITLE
game pause indefinitely if piority player joined game and tab out

### ISSUE THREAD

**Issue by Yuerino** [GQDeltex/ft_transcendence#422]

**Comment by Yuerino** [comment]
[hasFocus](https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus)

**Comment by GQDeltex** [comment]
But if we were to check if the window hasFocus, you would not be able to click out of the window or click on another browser tab. I don't think that's great behaviour. Also because the game doesn't start, the score is 0:0 anyways, so no points get lost if one reloads because of the hanging game. So I don't think we should stop the game if the window looses focus
