### ISSUE TITLE
Implement 2FA Authentication

### ISSUE THREAD

**Issue by Yuerino** [GQDeltex/ft_transcendence#49]

**Comment by dejanzivanov** [comment]
At the moment, in the backend, generation of the Quar code is possible after the user logs in.

How to test:

-  Login with intra
-  Use the postman
-  In header, create a Key with name "Cookie", value with the name jwt=insert_jwt_token_from_login_page_here


![jwt_postman](https://user-images.githubusercontent.com/77687815/193695379-cb0afae0-be8c-4209-a631-0b2bff18c337.png)

-  Body of the request should contain following data: 


![Screenshot_16](https://user-images.githubusercontent.com/77687815/193695789-8f0ebc7d-829e-4be6-ada3-38d8456f1f93.png)

-  And request should be post

After request has been sent we get a quar code that can be scanned with the Google Authenticator Application:


![Screenshot_17](https://user-images.githubusercontent.com/77687815/193695976-7aecabda-9948-4b62-9c0c-e25e37e16d4e.png)


![Screenshot_18](https://user-images.githubusercontent.com/77687815/193696381-c6070aae-7ea3-4c9a-8e1b-49e5be486bb1.png)

**Comment by dejanzivanov** [comment]
TODO:
- [ ] After user wants to activate 2FA, prompt the window to type the code, after the code is confirmed, 2FA will be activated, otherwise user will loose access to account.
-  [ ] change behaviour in code, so we dont need a whole user body of information, but rather only user ID and secret
- [ ] Link with the frontend.
